services:
  tauri:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - .:/app:cached
      - cargo-cache:/root/.cargo
      - ./src-tauri/target:/app/src-tauri/target
    working_dir: /app
    command: [ "sh", "-c", ". \"$NVM_DIR/nvm.sh\" && bun run tauri build --bundles appimage" ]
    # tty: true

volumes:
  cargo-cache: